project:
  type: website
website:
  title: "Phenological Shifts in the Ruby-Throated Hummingbird and the Cardinal Flower"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    includes:
        after_body: include/after_body.html
