project:
  type: website
  output-dir: .
website:
  title: "Shifts in the Ruby-Throated Hummingbird and the Cardinal Flower"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: spacelab
    includes:
        after_body: include/after_body.html
