project:
  type: website

website: Aubrey Monaco GEO511 Final Project
  title: "GEO 511 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    includes:
        after_body: include/after_body.html
