project:
  type: website
  output-dir: .
website:
  title: "GEO511 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: spacelab
    includes:
        after_body: include/after_body.html
